# Experiment: Stream Data Sampling and Filtering Using Python

---

### Aim:
To simulate a real-time data stream and implement fundamental stream processing techniques—specifically **Random Sampling** and **Condition-based Filtering**—using Python.

### Objectives:
1. Simulate a continuous data stream of numerical values using Python.
2. Implement **Random Sampling** to select a representative, unbiased subset of the stream.
3. Implement **Condition-based Filtering** using list comprehension to retain only elements satisfying a specific condition.
4. Analyze and compare the size and data retention percentage of the original, sampled, and filtered streams using Pandas.
5. Understand the key differences and practical use-cases of sampling (volume reduction) versus filtering (relevance extraction).

### Methodology Overview:
In real-world data science applications (e.g., IoT sensor telemetry, financial trading streams, network traffic logs), data arrives continuously at high velocities. Storing or processing every incoming data point can be computationally prohibitive.
- **Sampling** reduces the volume of the data stream by picking a representative subset without evaluating the content of individual elements.
- **Filtering** inspects each incoming element against a predefined condition and retains only data points of interest, discarding the rest.

### 1. Import Required Libraries
Before processing the stream, we import the necessary Python libraries:
- `pandas`: For creating structured tables and analyzing retention metrics.
- `numpy`: For numerical computations and statistical operations.
- `random`: Python's built-in module for simulating the stream and performing random sampling.

In [1]:
# Import required libraries
import pandas as pd
import numpy as np
import random

# Set random seed for reproducibility in laboratory evaluations
random.seed(42)
np.random.seed(42)

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Libraries imported successfully.")

Pandas version: 3.0.6
NumPy version: 2.5.3
Libraries imported successfully.

### 2. Generate Simulated Data Stream
A data stream is an incoming sequence of items. Here, we simulate a stream of 100 random numerical values between 1 and 100 using Python's `random.randint()`. The values are stored in a standard Python list.

In [2]:
# Generate a stream of 100 random numerical values between 1 and 100
stream_data = [random.randint(1, 100) for _ in range(100)]

# Display the original data stream
print("Original Data Stream (100 elements):")
print(stream_data)

# Display the total number of elements
print("\nTotal number of elements in the stream:", len(stream_data))

Original Data Stream (100 elements):
[82, 15, 4, 95, 36, 32, 29, 18, 95, 14, 87, 95, 70, 12, 76, 55, 5, 4, 12, 28, 30, 65, 78, 4, 72, 26, 92, 84, 90, 70, 54, 29, 58, 76, 36, 1, 98, 21, 90, 55, 44, 36, 20, 28, 98, 44, 14, 12, 49, 13, 46, 45, 78, 34, 6, 94, 59, 69, 16, 49, 11, 71, 38, 81, 80, 47, 74, 25, 91, 9, 6, 85, 30, 99, 38, 11, 30, 13, 49, 36, 59, 82, 47, 21, 48, 46, 27, 86, 35, 90, 88, 83, 10, 78, 82, 22, 69, 94, 32, 21]

Total number of elements in the stream: 100

### 3. Apply Random Sampling
**Sampling** selects a subset of elements from the data stream. It is used to reduce the data volume for downstream analysis without inspecting or biasing towards specific values.

Here, we randomly select 20 values from the original stream using `random.sample()`.

In [3]:
# Randomly select 20 values from the original stream using random.sample()
sample_size = 20
sampled_stream = random.sample(stream_data, sample_size)

# Display the sampled values
print(f"Sampled Stream ({sample_size} randomly selected values):")
print(sampled_stream)

# Display the sample size
print("\nSample size:", len(sampled_stream))

Sampled Stream (20 randomly selected values):
[49, 49, 36, 82, 35, 85, 90, 86, 36, 32, 21, 18, 70, 36, 44, 45, 95, 84, 30, 83]

Sample size: 20

### 4. Apply Filtering
**Filtering** evaluates a logical condition (predicate) on each data element in the stream. Only elements that satisfy the condition are retained.

Here, we filter the original data stream to retain only values greater than 50 using Python list comprehension.

In [4]:
# Filter the original data stream to retain only values greater than 50
filtered_stream = [x for x in stream_data if x > 50]

# Display the filtered values
print("Filtered Stream (Values > 50):")
print(filtered_stream)

# Display the number of filtered elements
print("\nNumber of filtered elements:", len(filtered_stream))

Filtered Stream (Values > 50):
[82, 95, 95, 87, 95, 70, 76, 55, 65, 78, 72, 92, 84, 90, 70, 54, 58, 76, 98, 90, 55, 98, 78, 94, 59, 69, 71, 81, 80, 74, 91, 85, 99, 59, 82, 86, 90, 88, 83, 78, 82, 69, 94]

Number of filtered elements: 43

### 5. Analyze the Results
We now compare:
- Original stream size
- Sampled stream size
- Filtered stream size
- Percentage of original data retained after sampling
- Percentage of original data retained after filtering

We organize these results in a structured Pandas DataFrame.

In [5]:
# Calculate stream sizes
original_size = len(stream_data)
sampled_size = len(sampled_stream)
filtered_size = len(filtered_stream)

# Calculate retention percentages
sampling_retention_pct = (sampled_size / original_size) * 100
filtering_retention_pct = (filtered_size / original_size) * 100

# Create comparison DataFrame using Pandas
comparison_df = pd.DataFrame({
    "Stream Operation": [
        "Original Stream",
        "Random Sampling (n = 20)",
        "Conditional Filtering (Value > 50)"
    ],
    "Element Count": [
        original_size,
        sampled_size,
        filtered_size
    ],
    "Retention Rate (%)": [
        "100.00%",
        f"{sampling_retention_pct:.2f}%",
        f"{filtering_retention_pct:.2f}%"
    ],
    "Selection Basis": [
        "Complete stream",
        "Random selection (independent of value)",
        "Condition check (value > 50)"
    ]
})

print("=== Stream Processing Comparison Summary ===")
comparison_df

=== Stream Processing Comparison Summary ===
Out[0]:
                     Stream Operation  ...                          Selection Basis
0                     Original Stream  ...                          Complete stream
1            Random Sampling (n = 20)  ...  Random selection (independent of value)
2  Conditional Filtering (Value > 50)  ...             Condition check (value > 50)

[3 rows x 4 columns]

                     Stream Operation  ...                          Selection Basis
0                     Original Stream  ...                          Complete stream
1            Random Sampling (n = 20)  ...  Random selection (independent of value)
2  Conditional Filtering (Value > 50)  ...             Condition check (value > 50)

[3 rows x 4 columns]

### 6. Sampling vs. Filtering: Comparison

Both sampling and filtering reduce the volume of data flowing through a stream processing pipeline, but they do so based on fundamentally different mechanisms:

#### What Sampling Does:
- **Random / Probabilistic Selection**: It selects an arbitrary subset of items without evaluating the contents or values of individual data points.
- **Volume Reduction**: Its primary purpose is to cut down bandwidth, storage, and CPU consumption while maintaining an unbiased statistical representation of the data.
- **Predictable Output Size**: The size of the output is directly controlled by the user (e.g., exactly 20 items or 20% of the stream).

#### What Filtering Does:
- **Predicate-Based Selection**: It inspects each arriving item and tests it against a specific condition (e.g., `value > 50` or `status == "ERROR"`).
- **Relevance Extraction**: Its primary purpose is to isolate critical items, alerts, or anomalies from uninteresting background data.
- **Dynamic Output Size**: The number of retained items is not predetermined; it depends entirely on how many elements satisfy the condition.

#### Comparison Table:
| Feature / Aspect | Stream Sampling | Stream Filtering |
| :--- | :--- | :--- |
| **Primary Goal** | Reduce overall volume while preserving statistical properties | Extract relevant, actionable, or critical items |
| **Selection Basis** | Random / uniform probability (content-agnostic) | Logical condition / threshold (content-aware) |
| **Output Size** | Fixed and predetermined | Variable (depends on stream contents) |
| **Preservation of Critical Events**| Might miss rare anomalies due to random omission | Guarantees all matching events are captured |
| **Typical Use Cases** | Load shedding, telemetry approximation, trend monitoring | Fraud detection, alarm triggers, error log extraction |

### 7. Conclusion

In this experiment, we implemented stream data sampling and filtering using Python:
1. **Sampling** reduced the volume of data processed from 100 elements to 20 elements (20% retention). This demonstrates how sampling reduces memory and computation bottlenecks without introducing value-based bias.
2. **Filtering** extracted only relevant data points meeting a specific criterion (values > 50), demonstrating how condition-based checks allow real-time systems to extract meaningful signals from noisy streams.
3. Together, sampling and filtering form fundamental building blocks for scalable stream data processing pipelines.

# Exercises and Assignments

This section contains solutions for the practical laboratory assignments:
1. Change the sample size from 20 to 10 and display the result.
2. Filter values greater than 80 instead of 50.
3. Generate a larger data stream containing 1000 values and compare the original, sampled, and filtered sizes.
4. Explain the difference between sampling and filtering using Markdown.
5. Apply sampling and filtering to another numerical dataset of your choice.

### Exercise 1: Change Sample Size from 20 to 10
Modify the sample size parameter to select 10 elements instead of 20 from the original 100-element stream.

In [6]:
# Exercise 1: Select 10 random values from the original stream
new_sample_size = 10
sampled_stream_10 = random.sample(stream_data, new_sample_size)

# Display results
print(f"Sampled Stream ({new_sample_size} elements):")
print(sampled_stream_10)
print("\nSample size:", len(sampled_stream_10))
print(f"Retention Percentage: {(len(sampled_stream_10) / len(stream_data)) * 100:.2f}%")

Sampled Stream (10 elements):
[44, 84, 21, 81, 46, 47, 16, 12, 76, 4]

Sample size: 10
Retention Percentage: 10.00%

### Exercise 2: Filter Values Greater Than 80 Instead of 50
Filter the original data stream with a stricter threshold to retain only values greater than 80.

In [7]:
# Exercise 2: Filter values greater than 80
filtered_stream_80 = [x for x in stream_data if x > 80]

# Display results
print("Filtered Stream (Values > 80):")
print(filtered_stream_80)
print("\nNumber of filtered elements (> 80):", len(filtered_stream_80))
print(f"Retention Percentage: {(len(filtered_stream_80) / len(stream_data)) * 100:.2f}%")

Filtered Stream (Values > 80):
[82, 95, 95, 87, 95, 92, 84, 90, 98, 90, 98, 94, 81, 91, 85, 99, 82, 86, 90, 88, 83, 82, 94]

Number of filtered elements (> 80): 23
Retention Percentage: 23.00%

### Exercise 3: Larger Data Stream (1000 Values) Comparison
Generate a larger simulated data stream containing 1,000 values between 1 and 1,000, sample 100 values (10%), filter values greater than 500, and compare their sizes using Pandas.

In [8]:
# Exercise 3: Generate a stream of 1000 random values between 1 and 1000
large_stream = [random.randint(1, 1000) for _ in range(1000)]

# Randomly sample 100 values (10% sample)
large_sampled = random.sample(large_stream, 100)

# Filter values greater than 500
large_filtered = [val for val in large_stream if val > 500]

# Compare sizes using a Pandas DataFrame
large_comparison_df = pd.DataFrame({
    "Stream Category": [
        "Large Original Stream",
        "Sampled Stream (10%)",
        "Filtered Stream (Values > 500)"
    ],
    "Element Count": [
        len(large_stream),
        len(large_sampled),
        len(large_filtered)
    ],
    "Retention Rate (%)": [
        "100.00%",
        f"{(len(large_sampled) / len(large_stream)) * 100:.2f}%",
        f"{(len(large_filtered) / len(large_stream)) * 100:.2f}%"
    ]
})

print("=== Large Data Stream (1000 Elements) Analysis ===")
large_comparison_df

=== Large Data Stream (1000 Elements) Analysis ===
Out[0]:
                  Stream Category  Element Count Retention Rate (%)
0           Large Original Stream           1000            100.00%
1            Sampled Stream (10%)            100             10.00%
2  Filtered Stream (Values > 500)            510             51.00%

                  Stream Category  Element Count Retention Rate (%)
0           Large Original Stream           1000            100.00%
1            Sampled Stream (10%)            100             10.00%
2  Filtered Stream (Values > 500)            510             51.00%

### Exercise 4: Conceptual Difference Between Sampling and Filtering

The key conceptual differences between stream sampling and stream filtering are:

1. **Criterion of Selection**:
   - **Sampling** is non-selective regarding the content of the data; it treats every incoming element with equal probability (uniform random sampling).
   - **Filtering** is strictly conditional; it inspects the data payload and tests whether it satisfies a specified rule (e.g., threshold crossing).

2. **Control Over Volume**:
   - **Sampling** gives direct control over output size or rate (e.g., exactly $k$ elements or a fixed sampling fraction $p$).
   - **Filtering** produces an output size dependent entirely on the underlying data distribution; if all items meet the criteria, no volume reduction occurs.

3. **Information Loss vs. Noise Removal**:
   - **Sampling** causes statistical approximation; rare anomalies may be accidentally dropped.
   - **Filtering** removes known irrelevant data points (noise) while guaranteeing that all events of interest are captured.

4. **Summary Comparison Table**:
| Dimension | Sampling | Filtering |
| :--- | :--- | :--- |
| **Input Evaluation** | Blind / content-agnostic | Conditional / content-aware |
| **Output Size** | Fixed & predictable | Variable & data-dependent |
| **Primary Use** | Load shedding, approximation | Event detection, noise reduction |

### Exercise 5: Apply Sampling and Filtering to Another Numerical Dataset
We apply stream sampling and filtering to an environmental monitoring dataset: simulated hourly temperature sensor readings (°C) over 50 hours (values between 15.0°C and 45.0°C).
- **Sampling**: Select 10 random readings for routine sensor health telemetry.
- **Filtering**: Extract temperature readings exceeding 38.0°C to trigger critical heat warning alerts.

In [9]:
# Exercise 5: Simulated Hourly Temperature Sensor Readings (°C)
sensor_temperatures = [round(random.uniform(15.0, 45.0), 1) for _ in range(50)]

print("Original Temperature Stream (50 readings in °C):")
print(sensor_temperatures)

# 1. Random Sampling: Select 10 readings for routine telemetry
sampled_temperatures = random.sample(sensor_temperatures, 10)
print("\nSampled Telemetry Readings (10 samples):")
print(sampled_temperatures)

# 2. Filtering: Extract critical heat alerts (> 38.0 °C)
heat_alerts = [temp for temp in sensor_temperatures if temp > 38.0]
print("\nFiltered Critical Heat Alerts (Readings > 38.0 °C):")
print(heat_alerts)

# Summary comparison DataFrame using Pandas and NumPy
sensor_summary_df = pd.DataFrame({
    "Stream Category": [
        "Full Sensor Stream",
        "Sampled Telemetry (Routine Check)",
        "Filtered Alerts (Critical Temp > 38°C)"
    ],
    "Reading Count": [
        len(sensor_temperatures),
        len(sampled_temperatures),
        len(heat_alerts)
    ],
    "Retention Rate (%)": [
        "100.00%",
        f"{(len(sampled_temperatures) / len(sensor_temperatures)) * 100:.2f}%",
        f"{(len(heat_alerts) / len(sensor_temperatures)) * 100:.2f}%"
    ],
    "Mean Temperature (°C)": [
        round(float(np.mean(sensor_temperatures)), 2),
        round(float(np.mean(sampled_temperatures)), 2),
        round(float(np.mean(heat_alerts)) if heat_alerts else 0.0, 2)
    ]
})

print("\n=== Temperature Sensor Stream Analysis ===")
sensor_summary_df

Original Temperature Stream (50 readings in °C):
[34.1, 37.6, 18.1, 15.4, 23.5, 29.4, 25.2, 44.0, 22.6, 40.9, 18.4, 17.0, 29.8, 32.3, 35.6, 19.6, 39.3, 43.5, 17.6, 22.4, 31.7, 27.5, 32.9, 33.6, 38.3, 26.4, 42.3, 23.9, 32.7, 27.9, 32.1, 16.8, 43.8, 18.0, 37.9, 33.8, 22.9, 17.4, 22.2, 31.6, 19.7, 27.3, 35.7, 29.1, 16.0, 23.6, 23.5, 40.8, 17.1, 22.0]

Sampled Telemetry Readings (10 samples):
[39.3, 19.7, 17.4, 35.7, 29.8, 23.9, 44.0, 37.9, 35.6, 40.9]

Filtered Critical Heat Alerts (Readings > 38.0 °C):
[44.0, 40.9, 39.3, 43.5, 38.3, 42.3, 43.8, 40.8]

=== Temperature Sensor Stream Analysis ===
Out[0]:
                          Stream Category  ...  Mean Temperature (°C)
0                      Full Sensor Stream  ...                  28.30
1       Sampled Telemetry (Routine Check)  ...                  32.42
2  Filtered Alerts (Critical Temp > 38°C)  ...                  41.61

[3 rows x 4 columns]

                          Stream Category  ...  Mean Temperature (°C)
0                      Full Sensor Stream  ...                  28.30
1       Sampled Telemetry (Routine Check)  ...                  32.42
2  Filtered Alerts (Critical Temp > 38°C)  ...                  41.61

[3 rows x 4 columns]